image: gradle:5.6.4-jdk11

stages:
  - build
  - test

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod +x ./gradlew

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  only:
    - master

test:
  stage: test
  script:
    - ./gradlew check
    - cat build/jacocoHtml/index.html | grep -o '<tfoot>.*</tfoot>'

  artifacts:
    reports:
      junit: build/test-results/test/TEST-*.xml



after_script:
